[package]
name = "rake"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.34", features = ["derive"] }
reqwest = { version = "0.12.15", features = ["blocking"] }
colored = "3.0.0"
crossbeam = "0.8.4"
