[package]
name = "rake"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "crates/fuzzer",
    "crates/reader",
    "crates/sender"
]

[dependencies]
fuzzer = { path = "crates/fuzzer"}
clap = { version = "4.5.34", features = ["derive"] }
