[package]
name = "fuzzer"
version = "0.1.0"
edition = "2024"

[dependencies]
reader = { path = "../reader" }
sender = { path = "../sender" }

reqwest = { version = "0.12.15", features = ["blocking"] }
crossbeam = "0.8.4"
colored = "3.0.0"
indicatif = "0.17.11"
